Importing library

In [1]:
from numpy import array #For Array
from numpy import random # For Randomly
from numpy import dot # For doing dot product
from random import choice

Activation function

In [2]:
import numpy as np

# step activation function
# activationFn = lambda x:0 if x<0 else 1 

# sigmoid activation function
#activationFn = lambda x: 1/(1+np.exp(-x))

# RELU activation function
#activationFn = lambda x: 0 if x<0 else x

# SOFTMAX activation function
activationFn = lambda x: np.exp(x) / np.sum(np.exp(x), axis=0)

error = []

Training dataset

In [3]:
dataset = [
           (array([0,0,1]),0),  # array([x,y,b],e) x,y=Input , b=bias , e Expected O/P to validate
           (array([0,1,1]),1), 
           (array([1,0,1]),1), 
           (array([1,1,1]),1), 
]
print(dataset)
print(array([0,0,1]),0)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]
[0 0 1] 0


Initializing Random numbers for weights

In [4]:
weights = random.rand(3)
weights

array([0.46596576, 0.29800899, 0.07401629])

initializing additional variables

In [5]:
r = 0.2 # learning rates
n = 100 # Number of Iteration

Training our model

In [6]:
for j in range(n):
  x, expected = choice(dataset)
  #print(x,expected)
  result = dot(weights,x)
  err = expected-activationFn(result)
  error.append(err)
  weights += r * err * x # calculta the correction factor, added to weights to improve o/p
  # If the expected value is bigger, the weights shoud be increased


Evaluating Model

In [7]:
  for x, _ in dataset:
    result = dot(x,weights)
    print("Input: {} ResultBAFn:{} ResultAFn:{}".format(x[:2],round(result,3),activationFn(result)))

Input: [0 0] ResultBAFn:-5.326 ResultAFn:1.0
Input: [0 1] ResultBAFn:-5.028 ResultAFn:1.0
Input: [1 0] ResultBAFn:-4.86 ResultAFn:1.0
Input: [1 1] ResultBAFn:-4.562 ResultAFn:1.0
