Importing library

In [1]:
from numpy import array #For Array
from numpy import random # For Randomly
from numpy import dot # For doing dot product
from random import choice

Activation function

In [2]:
activationFn = lambda x:0 if x<0 else 1 #step activation function

Training dataset

In [3]:
dataset = [
           (array([0,0,1]),0),  #array([x,y,b],e) x,y=Input , b=bias , e Expected O/P to validate
           (array([0,1,1]),1), 
           (array([1,0,1]),1), 
           (array([1,1,1]),1), 
]
print(dataset)
print(array([0,0,1]),0)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]
[0 0 1] 0


Initializing Random numbers for weights

In [11]:
weights = random.rand(3)
weights

array([0.30492366, 0.87572214, 0.5115862 ])

initializing additional variables

In [12]:
r = 0.2 # learning rates
n = 100 # Number of Iteration

Training our model

In [13]:
for j in range(n):
  x, expected = choice(dataset)
  #print(x,expected)
  result = dot(weights,x)
  err = expected-activationFn(result)
  weights += r * err * x # calculate the correction factor, added to weights to improve o/p
  # If the expected vlue is bigger, the weights shoud be increased


[1 0 1] 1
[1 1 1] 1
[0 0 1] 0
[0 0 1] 0
[1 0 1] 1
[0 0 1] 0
[1 1 1] 1
[0 1 1] 1
[0 0 1] 0
[1 1 1] 1
[0 0 1] 0
[1 1 1] 1
[1 0 1] 1
[1 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 0 1] 1
[1 0 1] 1
[1 0 1] 1
[1 1 1] 1
[1 1 1] 1
[0 1 1] 1
[1 1 1] 1
[1 1 1] 1
[0 1 1] 1
[0 1 1] 1
[1 1 1] 1
[1 0 1] 1
[0 1 1] 1
[0 0 1] 0
[1 0 1] 1
[1 0 1] 1
[1 0 1] 1
[1 0 1] 1
[0 0 1] 0
[1 1 1] 1
[0 1 1] 1
[1 0 1] 1
[0 0 1] 0
[1 1 1] 1
[0 0 1] 0
[0 0 1] 0
[0 1 1] 1
[1 1 1] 1
[0 1 1] 1
[0 1 1] 1
[1 1 1] 1
[1 0 1] 1
[1 0 1] 1
[1 1 1] 1
[0 0 1] 0
[0 0 1] 0
[1 0 1] 1
[0 0 1] 0
[0 1 1] 1
[0 0 1] 0
[1 0 1] 1
[1 1 1] 1
[0 0 1] 0
[0 0 1] 0
[1 0 1] 1
[0 0 1] 0
[1 0 1] 1
[1 1 1] 1
[0 1 1] 1
[1 1 1] 1
[0 0 1] 0
[0 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 0 1] 1
[1 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 1 1] 1
[0 1 1] 1
[1 0 1] 1
[1 0 1] 1
[0 0 1] 0
[0 1 1] 1
[0 0 1] 0
[0 0 1] 0
[0 0 1] 0
[0 0 1] 0
[0 0 1] 0
[1 0 1] 1
[1 0 1] 1
[0 0 1] 0
[1 1 1] 1
[0 0 1] 0
[1 0 1] 1
[1 1 1] 1
[1 0 1] 1
[0 1 1] 1
[1 1 1] 1
[1 1 1] 1
[1 0 1] 1
[0 0 1] 0
[1 0 1] 1


Evaluating Model

In [14]:
  for x, _ in dataset:
    result = dot(x,weights)
    print("Input: {} ResultBAFn:{} ResultAFn:{}".format(x[:2],round(result,3),activationFn(result)))

Input: [0 0] ResultBAFn:-0.088 ResultAFn:0
Input: [0 1] ResultBAFn:0.787 ResultAFn:1
Input: [1 0] ResultBAFn:0.217 ResultAFn:1
Input: [1 1] ResultBAFn:1.092 ResultAFn:1
